### PR TITLE
Make OpensearchProvider inherit ServiceLifecycleHook

### LINKED ISSUE #8092: bug: pod save/restore of elastic search domain fails to restart ES (2.0.1dev)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create an ElasticSearch domain.   Run pod save.   Restart LocalStack.   Run pod restore.   Domain still exists in config, but the ES software isn't downloaded/installed/started.

### Expected Behavior

That it restarts ES.   This worked in 1.14

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

localstack start -d 
awslocal es create-elasticsearch-domain --elasticsearch-version 7.7 --domain-name audit
localstack pod save file://$PWD/estest.pod
localstack stop
localstack start
localstack pod load file://$PWD/estest.pod

### Environment

```markdown
- OS: Mac 13.2.1
- LocalStack: 2.0.1dev
```

### Anything else?
Note the pod save/restore does preserve your ES domains, it just doesn't start/install ES.

No interesting messages from the localstack console

```
 💻 LocalStack CLI 2.0.0.post1

[15:22:37] starting LocalStack in Docker mode 🐳                                                                                                                                    localstack.py:142
2023-04-06T15:22:37.327  WARN --- [  MainThread] localstack_ext.plugins     : Unable to start DNS: cannot import name 'dns_server' from 'localstack_ext.services' (/opt/homebrew/lib/python3.11/site-packages/localstack_ext/services/__init__.py)
─────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ───────────────────────────────────────────────────────────────────────────
2023-04-06T15:22:37.413  WARN --- [  MainThread] localstack_ext.plugins     : failed to configure DNS: cannot import name 'dns_server' from 'localstack_ext.services' (/opt/homebrew/lib/python3.11/site-packages/localstack_ext/services/__init__.py)

LocalStack version: 2.0.1.dev
LocalStack Docker container id: 77863cef09a0
LocalStack build date: 2023-04-05
LocalStack build git hash: ae1dfbf9

2023-04-06T22:22:38.738  WARN --- [  MainThread] localstack.deprecations    : DEFAULT_REGION is deprecated (since 0.12.7) and will be removed in upcoming releases of LocalStack! LocalStack now has full multi-region support. Please remove this environment variable.
2023-04-06T22:22:38.825  WARN --- [-functhread3] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-04-06T22:22:38.825  WARN --- [-functhread3] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-04-06T22:22:38.827  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-04-06T22:22:38.827  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
2023-04-06T22:23:11.871  INFO --- [   asgi_gw_0] localstack.request.http    : GET / => 200
2023-04-06T22:23:11.882  INFO --- [   asgi_gw_0] localstack.request.http    : GET /_localstack/pods/environment => 200
2023-04-06T22:23:12.034  INFO --- [   asgi_gw_0] localstack.request.http    : POST /_localstack/pods => 201

```

### PR DESCRIPTION
**Pull request by GREsau**
Fixes #8092

## Motivation
`OpensearchProvider` implements the methods `on_after_state_load`, `on_before_state_reset`, and `on_before_stop`. However, they currently are never invoked because the provider is not a `ServiceLifecycleHook` ([which is checked here](https://github.com/localstack/localstack/blob/master/localstack/services/plugins.py#L165-L168)). This causes loaded elasticsearch/opensearch state to not behave correctly (i.e. #8092).

I didn't add a new test for this because I'm not sure where it should go - are there existing tests covering persistence? Fortunately, this change itself is fairly minimal.

### CODE REVIEW

**Comment by GREsau** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by GREsau** [comment]
[The contributing guide](https://github.com/localstack/localstack/blob/master/CONTRIBUTING.md) says "When creating a PR, classify the size of your change with setting a semver label" - unfortunately I can't do that because I don't appear to have permissions to add labels to the PR!

Presumably this would be a `semver: patch` change

**Review by alexrashed — APPROVED** [review]
Hi @GREsau!
Thanks for your contribution! The code change is looking good, thanks for digging into this!
I will merge this now and it will up in the latest image with the next successful build on master.
However, we are discontinuing the Community Cloud Pods with LocalStack v3 (and then this feature won't work anymore in LocalStack Community). For more details concerning the release (and the timeline) please take a look at https://github.com/localstack/localstack/issues/9519.

**Comment by GREsau** [comment]
Understood - I was hoping this was soon enough to be included in an additional 2.X.X release, but no big deal if not
