### ISSUE TITLE
bug: error when re-subscribing an SQS queue to an SNS topic

### ISSUE THREAD

**Issue by agilethomas** [localstack/localstack#9058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When re-subscribing an SQS queue to an SNS topic, localstack throws an error. This occurs via command line and with our nodejs implementation.

    An error occurred (InternalError) when calling the Subscribe operation (reached max retries: 2): exception while calling sns.Subscribe: 'NoneType' object has no attribute 'get'
    22:21:18 - awscliv2 - ERROR - Command failed with code 254

### Expected Behavior

Since the queue is subscribed to the topic already, it should be a no-op and simply return the same subscription arn.

This worked in older versions of localstack, and since it works fine with AWS, I would think this behavior should not throw an error in localstack.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
    Downloaded the "onefile" tar.gz file (localstack-cli-2.2.0-linux-amd64-onefile.tar.gz)

    GATEWAY_LISTEN=0.0.0.0:4566 \
            DNS_ADDRESS=0 \
            FORCE_NONINTERACTIVE=true \
            DOCKER_FLAGS=-d \
            localstack start --docker

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

**Create queue**

    aws sqs create-queue --endpoint-url http://localhost:4566 --profile localstack --queue-name TEST-QUEUE
    {
        "QueueUrl": "http://localhost:4566/000000000000/TEST-QUEUE"
    }

**Create topic**

    aws sns create-topic --endpoint-url http://localhost:4566 --profile localstack --name TEST-TOPIC
    {
        "TopicArn": "arn:aws:sns:us-east-1:000000000000:TEST-TOPIC"
    }

**Get queue arn**

    aws sqs get-queue-attributes --attribute-names QueueArn --queue-url http://localhost:4566/000000000000/TEST-QUEUE --endpoint-url http://localhost:4566 --profile localstack 
    {
        "Attributes": {
            "QueueArn": "arn:aws:sqs:us-east-1:000000000000:TEST-QUEUE"
        }
    }

**Subscribe and then resubscribe the queue to topic**

    aws sns subscribe --endpoint-url http://localhost:4566 --profile localstack --notification-endpoint arn:aws:sqs:us-east-1:000000000000:TEST-QUEUE --topic-arn arn:aws:sns:us-east-1:000000000000:TEST-TOPIC --protocol sqs
    {
        "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:TEST-TOPIC:71dbdc5d-7fcf-4bd8-83ca-34c048dfe437"
    }

    aws sns subscribe --endpoint-url http://localhost:4566 --profile localstack --notification-endpoint arn:aws:sqs:us-east-1:000000000000:TEST-QUEUE --topic-arn arn:aws:sns:us-east-1:000000000000:TEST-TOPIC --protocol sqs

    An error occurred (InternalError) when calling the Subscribe operation (reached max retries: 2): exception while calling sns.Subscribe: 'NoneType' object has no attribute 'get'
    22:21:18 - awscliv2 - ERROR - Command failed with code 254

### Environment

```markdown
- OS: Ubuntu 16.04
- LocalStack: 2.2.0
```

**Comment by bentsku** [comment]
Hello! Yes, this is a regression, and is already fixed with #9055, we are going to merge it soon. This is a duplicate of #9054, so I'll close the issue! Thanks a lot for the report

**Comment by agilethomas** [comment]
I started writing this out yesterday and it looks like the other issue was opened between then and when I submitted. Thanks for the quick response.

**Comment by bentsku** [comment]
Thanks a lot for reporting the issue, no worries for the duplicate 😄 the PR just got merged, so the new image should be out in around an hour or so.
