### ISSUE TITLE
Unable to run terraform to localstack from docker container.

### ISSUE THREAD

**Issue by mirak94** [localstack/localstack#718]
I'm trying to run terraform (which I have to run inside docker container) to create AWS resources into localstack, and I'm facing the following problem:
terraform-provider-aws is making https post request `https://iam.amazonaws.com/getUser&Version=X`. In this case I've to forward that request to localstack but I can not find a way to do so through localstack, I believe this is something missing.

Could anyone please help?
Thank you very much in advance.

**Comment by jonaskint** [comment]
I've managed to point terraform to my localstack setup with the following provider configuration:
```
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "anaccesskey"
  secret_key                  = "asecretkey"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  s3_force_path_style         = true

  endpoints {
    s3     = "http://localhost:4572"
    sqs    = "http://localhost:4576"
    lambda = "http://localhost:4574"
    sns    = "http://localhost:4575"
  }
}
```

**Comment by mirak94** [comment]
@jonaskint Thank you for sharing this with me.
I'm using a pretty much similar configuration to yours, however, terraform was making that post request I've shared above: `https://iam.amazonaws.com/getUser&Version=X`, which doesn't go to localstack (from my side), and if I directed it to localstack, how should it be caught/handled?

**Comment by jonaskint** [comment]
are you sure you enabled:
```
  skip_credentials_validation = true
  skip_metadata_api_check     = true
``` ?

**Comment by mirak94** [comment]
Also opened this on terraform-aws provider, as I don't get why this request is made although I'm skipping the credential validation:
https://github.com/terraform-providers/terraform-provider-aws/issues/4213

**Comment by mirak94** [comment]
@jonaskint By the way, all working fine when running from local, and I believe terraform doesn't make that post request, only when I run from inside a docker container.

**Comment by jonaskint** [comment]
@mirak94 i've managed to reproduce locally as well. Just do '''export TF_LOG=1''' and you'll see several calls to the iam backend.

**Comment by mirak94** [comment]
@jonaskint That's right.
Is there any hack to avoid such a call?

**Comment by jonaskint** [comment]
I think it might be a bug in terraform as we already use the "skip_credentials_validation" part. I've switched to aws cli commands for now as the project that will use it is small enough.

**Comment by mirak94** [comment]
Problem disappeared when I increased localstack version.

**Comment by Ghazgkull** [comment]
I still see this same problem, using the latest localstack/localstack image published on docker hub.

**Comment by mcaulifn** [comment]
same thing, provider is making a call to IAM

**Comment by Ghazgkull** [comment]
@mirak94 This problem persists in the current version of Localstack. I suspect it went away for you because you coincidentally authenticated your terminal to AWS. Can you please reopen this issue?

**Comment by mirak94** [comment]
@Ghazgkull That's correct. 
Re-opening the issue.

**Comment by jkieberking** [comment]
downgrading the aws provider version fixed this for me:
```
variable "base_dir" {
  type    = "string"
  default = "../../../.."
}

variable "access_key" {
  type    = "string"
  default = "test-access"
}
variable "secret_key" {
  type    = "string"
  default = "test-secret"
}
variable "region" {
  type    = "string"
  default = "us-east-1"
}

variable "lambda" {
  type    = "string"
  default = "http://localhost:4574"
}
variable "apigateway" {
  type    = "string"
  default = "http://localhost:4567"
}

provider "aws" {
  version = "~> 1.25"
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
  skip_credentials_validation = true
  skip_metadata_api_check = true
  s3_force_path_style = true
  endpoints {
    lambda = "${var.lambda}"
    apigateway = "${var.apigateway}"
  }
}

data "archive_file" "lambda" {
  type = "zip"
  source_file = "${var.base_dir}/lambda/testFunction.py"
  output_path = "${var.base_dir}/lambda/build/testFunction.zip"
}

resource "null_resource" "null_iam" {
}

resource "aws_lambda_function" "test_lambda" {
  filename         = "${data.archive_file.lambda.output_path}"
  function_name    = "test_lambda"
  role             = "${null_resource.null_iam.id}"
  handler          = "testFunction.handler"
  source_code_hash = "${base64sha256(file("${data.archive_file.lambda.output_path}"))}"
  runtime          = "python3.6"
}

**Comment by patelvijayg** [comment]
I am not able to run in docker container at (https://labs.play-with-docker.com).
I have run the following command start container
docker run -itd -p 4567-4593:4567-4593  localstack/localstack

Error logs
`
* Debug mode: off
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2019-03-28T19:41:02:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
2019-03-28T19:41:15:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2019-03-28T19:41:30:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
2019-03-28T19:41:40:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2019-03-28T19:42:04:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
2019-03-28T19:42:13:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
2019-03-28T19:42:22:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2019-03-28T19:42:34:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
2019-03-28T19:42:47:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2019-03-28T19:42:56:WARNING:infra.pyc: Service "s3" not yet available, retrying...
Waiting for all LocalStack services to be ready
2019-03-28T19:43:04:ERROR:localstack.services.s3.s3_starter: S3 health check failed:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 23, in check_s3
    wait_for_port_open(DEFAULT_PORT_S3_BACKEND)
  File "/opt/code/localstack/localstack/utils/common.py", line 362, in wait_for_port_open
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 395, in retry
    raise raise_error
Exception

2019-03-28T19:43:04:WARNING:infra.pyc: Service "s3" not yet available, retrying...
2019-03-28T19:43:04:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 408, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

Error starting infrastructure: 'NoneType' object has no attribute '__getitem__' Traceback (most recentcall last):
  File "/opt/code/localstack/localstack/services/infra.py", line 584, in start_infra
    check_infra(apis=apis)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 415, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

2019-03-28 19:43:07,113 INFO exited: infra (exit status 0; expected)
ERROR: 'NoneType' object has no attribute '__getitem__'
2019-03-28 19:43:08,116 INFO spawned: 'infra' with pid 1312
(. .venv/bin/activate; exec bin/localstack start)
Waiting for all LocalStack services to be ready
2019-03-28 19:43:09,127 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.
Starting mock SES (http port 4579)...
Starting mock CloudWatch Logs (http port 4586)...
Starting mock Redshift (http port 4577)...
Starting mock CloudFormation (http port 4581)...
Starting mock Firehose service (http port 4573)...
 * Serving Flask app "firehose_api" (lazy loading)
Starting mock Route53 (http port 4580)...
 * Environment: production
Starting mock ES service (http port 4578)...
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Serving Flask app "es_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
`

**Comment by whummer** [comment]
> It works with latest aws provider version (v1.37.0)

Great - thanks everyone for digging into this issue. Please create follow-up issues if there are any other problems with Terraform integration. Thanks

**Comment by asomov** [comment]
It looks like it is back in 
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.31"
    }
I reported in issue for Terraform provider: https://github.com/hashicorp/terraform-provider-aws/issues/18039
