### ISSUE TITLE
Deprecated boto3 calls required to interact with localstack S3

### ISSUE THREAD

**Issue by rjaduthie** [localstack/localstack#1064]
Localstack==0.8.8, Python==3.6.7, Boto3==1.9.68

Attempting something like:
```python

import boto3

s3_client = boto3.client("s3")
s3_client.create_bucket(Bucket="test-bucket")

notification_config = {
    "TopicConfiguration": [],
    "QueueConfiguration": [],
    "LambdaFunctionConfiguration": [],
}
s3_client.put_bucket_notification_configuration(
    Bucket="test-bucket", NotificationConfiguration=notification_config
)
```

This raises an error in the Python execution:
```
botocore.exceptions.ClientError: An error occurred (502) when calling the PutBucketNotificationConfiguration operation (reached max retries: 4): Bad Gateway
```
and also the localstack execution:
```
2018-12-20T11:38:03:ERROR:localstack.services.generic_proxy: Error forwarding request: 'list' object has no attribute 'get' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 196, in forward
path=path, data=data, headers=forward_headers)
File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 458, in forward_request
response = handle_notification_request(bucket, method, data)
File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 391, in handle_notification_request
events = config.get('Event')
AttributeError: 'list' object has no attribute 'get'
```

HOWEVER, using the deprecated version seems to work:

```python
s3_client.put_bucket_notification(
    Bucket="test-bucket", NotificationConfiguration=notification_config
)
```

Note that the payload for the two functions is not the same; this might be the reason for the problem, if   the two functions have been wired to the same s3_listener.py code (I need to check). The new method has different keys and mandates `list` objects for each type of configuration, whilst the deprecated version was expecting `dict`.  It seems the idea is that a bucket may have multiple configurations (lending itself to a `list`) and that if an empty list is supplied the bucket's configuration is reset to having no notifications.

**Comment by whummer** [comment]
Thanks for reporting @rjaduthie . This seems to be working with the latest version. I had to slightly adjust your script to get it working on my machine (Mac OS, Python 3.7):
```
import boto3

s3_client = boto3.client("s3", endpoint_url="http://localhost:4572")
s3_client.create_bucket(Bucket="test-bucket")

notification_config = {
    "TopicConfigurations": [],
    "QueueConfigurations": [],
    "LambdaFunctionConfigurations": [],
}
s3_client.put_bucket_notification_configuration(
    Bucket="test-bucket", NotificationConfiguration=notification_config
)
```
Please re-open this issue with more details if the problem persists. Thanks
