### ISSUE TITLE
Documentation Update Request re Java SDK

### ISSUE THREAD

**Issue by nsavageJVM** [localstack/localstack#1286]
### Updates for  Java sdk re  lambda/ kinesis issues 
Lambda

Classpath dependencies and aws sdk version conflicts
Currently the localstack lambda  runtime for java uses the  localstack-utils-XXX-fat.jar for classpath dependencies.
If you are using 3rd party jars in a ‘lib’ directory or finding conflicts with aws java sdk versions  [see](https://github.com/localstack/localstack/issues/1031) for example, source of  issues lies in the dependencies and versions in this jar. 
One option would be to add/update the versions in the java pom.xml in  /ext/java/ then  build and run localstack from source.

For the lambda handler the current codebase is unable to handle custom pojos [670](https://github.com/localstack/localstack/issues/670)

Kinesis (Java sdk)

The new java [KCL kinesis client library](https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html) is not supported [983](https://github.com/localstack/localstack/issues/893). 

For the supported [ Kinesis client version ](https://github.com/awslabs/amazon-kinesis-client)  works with version 1.8.8 

For Kinesis subscriber you may  need to point the client to a local dynamodb for the leasing tables 

Some general issues

Go lambda runtime is not currently supported
For S3 static website content type returned by logstack is `application/xml`  [854](https://github.com/localstack/localstack/issues/854)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-96) by [Unito](https://www.unito.io/learn-more)

**Comment by Ghilteras** [comment]
Looks like `localstack-utils` is missing AWS Organizations classes as well, I wrote a Lambda that interacts with AWS Organizations with Localstack and I get

```
Caused by: java.lang.NoClassDefFoundError: com/amazonaws/services/organizations/AWSOrganizationsClientBuilder
```

even if that class is clearly accessible in my local code.

**Comment by artembilan** [comment]
Also it look like this one has to be mentioned as well:
```
static {
	System.setProperty(SDKGlobalConfiguration.AWS_CBOR_DISABLE_SYSTEM_PROPERTY, "true");
}
```

See Kinesalite docs: https://github.com/mhart/kinesalite#cbor-protocol-issues-with-the-java-sdk

**Comment by whummer** [comment]
Thanks for reporting @nsavageJVM @Ghilteras @artembilan . The Lambda execution environment has been significantly reworked in the meantime - this should (hopefully) no longer be an issue with the default Docker-based Lambda executor. Please let us know if the problem persists with the `latest` Docker image. Thanks for your help!
