### PR TITLE
s3: fix replay for Authorization header from version 2

### PR DESCRIPTION
**Pull request by naspeh**
Related issue: https://github.com/localstack/localstack/issues/4297

The bug was introduced by https://github.com/localstack/localstack/pull/4033

An error was like this (reproduced in the test):
```
tests/unit/utils/test_persistence.py:89: AssertionError
-------------------------------------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------------------------------------
ERROR    werkzeug:_internal.py:225 Error on request:
Traceback (most recent call last):
  File "/opt/localstack/env/lib/python3.9/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/localstack/env/lib/python3.9/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/localstack/env/lib/python3.9/site-packages/moto/server.py", line 204, in __call__
    backend_app = self.get_application(environ)
  File "/opt/localstack/env/lib/python3.9/site-packages/moto/server.py", line 164, in get_application
    host = self.infer_service_region_host(environ)
  File "/opt/localstack/env/lib/python3.9/site-packages/moto/server.py", line 91, in infer_service_region_host
    credential_scope = auth.split(",")[0].split()[1]
IndexError: list index out of range
```

### CODE REVIEW

**Comment by whummer** [comment]
Nice - thanks for this fix @naspeh ! 🎉
