### ISSUE TITLE
Unable to load compiled python module

### ISSUE THREAD

**Issue by abelino** [localstack/localstack#319]
https://github.com/eawsy/aws-lambda-go-shim

I'm not too familiar with python, but I believe the above compiles a python module. So we see a folder structure like so (within generated package.zip):

```
package/
  handler.so
  handler/
    __init__.pyc
    proxy.pyc
    runtime.so
```

However, localstack expects to find `handler.py` instead. :( So we see the following issue:
```
localstack_1  | 2017-09-14T11:08:43:WARNING:localstack.services.awslambda.lambda_api: Unable to find handler script in Lambda archive.
localstack_1  | 2017-09-14T11:08:43:WARNING:localstack.services.awslambda.lambda_api: Unknown error: 'Response' object has no attribute 'update'
localstack_1  | 2017-09-14T11:08:43:WARNING:localstack.services.awslambda.lambda_api: Function already exist: test
```

The interesting part is that localstack doesn't halt, but actually creates the func... or at least it shows up in the dashboard.

<img width="487" alt="screen shot 2017-09-14 at 4 09 55 am" src="https://user-images.githubusercontent.com/7852183/30426918-b19d5cc0-9902-11e7-9ac0-52581deb3a52.png">

**Comment by whummer** [comment]
Thanks for reporting @abelino .
1) regarding the "Function already exist" error, that's a bug. Will be fixed asap.
2) regarding the "Unable to find handler script" error, afaik it is usually not good practice to work with compiled Python files. They may be compatible across operating systems, but not across Python versions. Is there any specific reason why you cannot put the python source files into the Lambda archive? Does this even work in the real AWS Lambda environment?

**Comment by whummer** [comment]
Point (1) should be fixed in #342

**Comment by abelino** [comment]
@whummer thanks for the amazing turn around time.

For point 2. I was testing the following shim https://github.com/eawsy/aws-lambda-go-shim to be able to run golang func on aws lambda. It works on aws lambda. So I naturally assumed it would work on localstack since python2.7 runtime is supported on localstack. Not sure what the best approach to fix, since I'm not familiar with python or if you guys would even consider looking into the matter?

**Comment by tobowers** [comment]
I'm also trying to test my aws-lambda-go-shim files on localstack. aws-lambda-go-shim uses go plugin compiling to make a c library and then this bit of code https://github.com/eawsy/aws-lambda-go-shim/blob/master/src/runtime.c to allow python to interop with the go code. That's why there isn't really any python source to speak of.

**Comment by tobowers** [comment]
@abelino did you ever get anything to work here? I'm thinking maybe I add my own handler.py and rezip for specifically localstack execution?

**Comment by whummer** [comment]
Closing as outdated. Please open follow-up issues if the problem persists. Thanks
