### PR TITLE
s3: fix replay tests for CI

### PR DESCRIPTION
**Pull request by naspeh**
Skip replay tests introduced by #4985 for `Pro` integration tests, as we skip `replay` in `Pro` because of the different implementation of persistency.

Because of these lines in `localstack-ext`: https://github.com/localstack/localstack-ext/blob/833b345a9ecbd0f84bcbba6199d21be0cc34e7c6/localstack_ext/utils/persistence.py#L146-L148

We get this error
```
        resp = persistence.replay_command(payload)
>       assert resp.status_code == 200
E       AttributeError: 'NoneType' object has no attribute 'status_code'
```

Failed runs:
- https://github.com/localstack/localstack/runs/4290802930?check_suite_focus=true

### CODE REVIEW

**Comment by naspeh** [comment]
Hm, it still fails...

**Comment by naspeh** [comment]
@whummer it's green now, please review.

**Review by whummer — APPROVED** [review]
Great catch @naspeh ! 👍
